apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
spec:
  serviceName: "vault"
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: hashicorp/vault:latest
        args:
          - "server"
          - "-config=/vault/config/vault.hcl"
        ports:
        - containerPort: 8200
          name: vault
        volumeMounts:
        - name: config
          mountPath: /vault/config
        - name: certs
          mountPath: /vault/certs
        - name: file-backend
          mountPath: /vault/file
        - name: raft-backend
          mountPath: /vault/raft
        securityContext:
          capabilities:
            add: ["IPC_LOCK"]
      volumes:
      - name: config
        configMap:
          name: vault-config
      - name: certs
        secret:
          secretName: vault-tls
      - name: file-backend
        emptyDir: {}
      - name: raft-backend
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: vault
spec:
  ports:
    - port: 8200
      targetPort: 8200
      protocol: TCP
      name: vault
  selector:
    app: vault
  type: ClusterIP 