apiVersion: v1
kind: Secret
metadata:
  name: vault-tls
  labels:
    app: vault
type: Opaque
data:
  vault.crt: <base64-encoded-cert>
  vault.key: <base64-encoded-key>
# Replace <base64-encoded-cert> and <base64-encoded-key> with your own base64-encoded cert and key 